name: 'Get the datetime string'
description: 'use it to get the datetime.'
inputs:
  tz1:
    description: 'Pre-slash Locale of the datetime (e.g., 'America' of 'America/New_York', see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for full list)'
    required: false
    default: 'Etc'
  tz2:
    description: 'Post-slash Locale of the datetime (e.g., 'New_York' of 'America/New_York', see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for full list)'
    required: false
    default: 'Greenwitch'
  dateformat_override:
    description: 'time zone of the datetime'
    required: false
    default: 'Greenwitch'
outputs:
  datetime_str: #
    description: 'date and time'
runs:
  using: 'node12'
  main: 'action.js'
branding:
  icon: 'terminal'
  color: 'green'
