#===================================================================================
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com.cn
#===================================================================================

name: CI

on: [push]

env:
  INPUT_TZ1: Etc
  INPUT_TZ2: Greenwitch

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get the datetime
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'America'
          tz2: 'Los_Angeles'

      - name: Print the datetime
        run: |
          echo ${{ steps.get_datetime.outputs.datetime_str }}
        shell: bash

    steps:
      - name: Override the dateformat
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'America'
          tz2: 'New_York'
          dateformat_override: '"%Y-%m-%d_LOL_OVERRIDDEN"'

      - name: Print the datetime
        run: |
          echo ${{ steps.get_datetime.outputs.datetime_str }}
        shell: bash
