#===================================================================================
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com.cn
#===================================================================================

name: CI

on: [push]

env:
  INPUT_TZ1: Los_Angeles
  INPUT_TZ2: New_York

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get the datetime
        id: get_datetime
        uses: mcgrue/get_datetime@master
        with:
          tz1: 'Los_Angeles'
          tz2: 'New_York'

      - name: Print the datetime
        run: |
          echo ${{ steps.get_datetime.outputs.datetime_str }}
          echo "lol"
        shell: bash
